name: 'Lint PR Title'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request title
      - uses: dreampulse/action-lint-pull-request-title@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowed-pull-request-types: chore,feat,fix,feat!
